name: YouTube Shorts Auto Upload

on:
  schedule:
    - cron: "0 */5 * * *"   # har 5 ghante run hoga
  workflow_dispatch:        # manually run karne ka option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests moviepy google-api-python-client google-auth google-auth-oauthlib pillow

      - name: Write secrets to files
        run: |
          echo '${{ secrets.CLIENT_SECRET_JSON }}' > client_secret.json
          echo '${{ secrets.TOKEN_JSON }}' > token.json

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
        
