name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # every 5 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Write secrets to files
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$TOKEN_JSON" > token.json
          echo "$CONFIG_JSON" > config.json

      - name: Run video generation + upload
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "✅ Script started..."
          python main.py
          
